name: test
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: astra tests
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') 
        && !contains(github.event.head_commit.message, '[skip ci]') 
        && !contains(github.event.pull_request.title, '[ci skip]')"
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: make maven wrapper executable
        if: contains(matrix.os, 'win') == false
        run: chmod +x ./mvnw

      - name: run all test
        run: make test-all
